### ISSUE TITLE
When use this tool in universal web app , it will throw error on desktop browser!

### ISSUE THREAD

**Issue by liwonder** [kudago/smart-app-banner#102]
https://github.com/kudago/smart-app-banner/blob/ca24c7c4150e43d83f89fe601c119f4cf4bd90ed/index.js#L83

I think this line caused this error, when view the web app in desktop browser, the type will be undefined.

@dy FYI

**Comment by alexeylindin** [comment]
@liwonder could you please check your version number.  This should work in 1.5.1

**Comment by liwonder** [comment]
Thanks @AlexeyLyndin, saw the changes there, and I was complain about the version 1.5.0.
I have placed the constructor into a "try...catch" to prevent the error from showing in console! : )

**Comment by alexeylindin** [comment]
@liwonder looks like i could close this issue, isn't it?

**Comment by liwonder** [comment]
Yes, thanks! @AlexeyLyndin
