### ISSUE TITLE
Bower Main Files not available

### ISSUE THREAD

**Issue by kryptografisch** [kudago/smart-app-banner#105]
Current Master Branch does not include a valid version of bower.json main property. 
Main files (smart-app-banner.css, smart-app-banner.js) cannot be found, since the files are located in subdirectory "dist".
Please update bower files. 
Furthermore I would suggest adding version tags in git as well to make new versions available for bower.

**Comment by GabLeRoux** [comment]
For version tag, refer to #92 and #59
