### ISSUE TITLE
false catch Android on win8.1 and Spartan

### ISSUE THREAD

**Issue by iamstarkov** [kudago/smart-app-banner#15]
It seems like windows phone 8.1 Update (and spartan) has android in its user agent. 
https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx

```
// Project Spartan for Windows Phone 
Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; DEVICE INFO) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Mobile Safari/537.36 Edge/12.0

// Internet Explorer for Windows Phone 8.1 Update 
Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 520) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537
```

**Comment by iamstarkov** [comment]
Maybe it’s better to rely on external well-tested npm package?

**Comment by dy** [comment]
It's a good idea. Which package may fit?

**Comment by iamstarkov** [comment]
dunno, can you check npmjs for me?

**Comment by dy** [comment]
Ok. I just need to spare a time for that.

**Comment by iamstarkov** [comment]
@dfcreative will spend few hours on this issue. Can I do some refactoring as well?

**Comment by iamstarkov** [comment]
@dfcreative I have done 
![xwgccap0_jq](https://cloud.githubusercontent.com/assets/559321/8573075/0a9d938c-2590-11e5-8b31-a9bf8578911e.jpg)

**Comment by iamstarkov** [comment]
checked, working as suppoused
