### ISSUE TITLE
Create tag with version number for Rails Assets

### ISSUE THREAD

**Issue by tannermares** [kudago/smart-app-banner#18]
Would love to add `smart-app-banner` to [rails-assets](https://rails-assets.org). It is requesting that a version number be present for it to use. I believe this is done through making a tag with the version number. Thanks for your work on this!

![image](https://cloud.githubusercontent.com/assets/1806545/8065731/3f3849c0-0e98-11e5-8f53-71a6311a248d.png)

**Comment by iamstarkov** [comment]
@kudago can you do something?

**Comment by DaSchTour** [comment]
This would also be great for bower. This shouldn't be that much work to add some tags.

**Comment by dy** [comment]
Please tell if still actual.
