### ISSUE TITLE
Need Array.prototype.forEach for IE8

### ISSUE THREAD

**Issue by vzilla** [kudago/smart-app-banner#2]
smartbanner.js

Array.prototype.forEach = function(callback, thisObj) {
    for (var i = 0,len = this.length; i < len; i++)
        callback.call(thisObj, this[i], i, this);
};

**Comment by glibin** [comment]
Хорошо бы оформить в пулл-реквест :)

**Comment by iamstarkov** [comment]
давайте использовать autopolyfiller здесь

**Comment by dy** [comment]
Use 

``` html
<script src="https://cdn.polyfill.io/v1/polyfill.js?features=default,Array.prototype.forEach"></script>
```

or alike here.
You can use `curl` to fetch needed polyfill once into a file.
