### ISSUE TITLE
Invalid bower version

### ISSUE THREAD

**Issue by Alexandre-io** [kudago/smart-app-banner#37]
We need to update the bower.json to the same version as package.json (1.1.3) and create a release into github otherwise we are unable to select the version with bower.

**Comment by kelsin** [comment]
:+1: right now we can only install version '*' with bower which is unsafe.

**Comment by DaSchTour** [comment]
Can someone please add tags to this repo?

**Comment by dy** [comment]
Please tell if still actual.
