### ISSUE TITLE
Include a minified version of css and js

### ISSUE THREAD

**Issue by fabiomlferreira** [kudago/smart-app-banner#46]
I think this module should include a minified version of js and css files. It's a great help for if we use this script in production environment.

**Comment by dy** [comment]
Sure, using minified js and css in production is usually a good thing, you can do it with modules like uglifyjs, postcss-csso and others.
As for keeping minified code in repositorium - that is usually not a good idea, as it forces huge diffs in commits or obliges using release practice, which is painsome for small modules.
So these tasks are left up to users, it is definitely not a goal of a project.
