### ISSUE TITLE
ccjs not found when building package

### ISSUE THREAD

**Issue by d-a-n** [kudago/smart-app-banner#57]
The build command uses ccjs and fails because this tool is not installed as a dev dependency.

```
browserify index.js -s SmartBanner | ccjs - > smart-app-banner.js
```

**Comment by dy** [comment]
Well it works for me, even at win7 machine.
Do `npm install` first and then `npm run build`. If nothing - update browserify/node/npm.

**Comment by linuxonrails** [comment]
It works for me too (ubuntu linux).

**Comment by dy** [comment]
Ok please tell if actual, I will reopen.
