### ISSUE TITLE
Add version tag for bower install, plz

### ISSUE THREAD

**Issue by avdeev** [kudago/smart-app-banner#59]

**Comment by ghost** [comment]
:+1:

**Comment by DaSchTour** [comment]
As mentioned in #18, #37, #50

**Comment by ghost** [comment]
well yes, but why there aren't any tags in git? Having in `bower.json`:

``` json
"dependencies": {
    "smart-app-banner": "1.3.0"
  }
```

 ends up with an error:

```
bower smart-app-banner#1.3.0       not-cached https://github.com/kudago/smart-app-banner.git#1.3.0
bower smart-app-banner#1.3.0          resolve https://github.com/kudago/smart-app-banner.git#1.3.0
bower smart-app-banner#1.3.0     ENORESTARGET No tag found that was able to satisfy 1.3.0

Additional error details:
No versions found in https://github.com/kudago/smart-app-banner.git
```

Please add corresponding tags to git repository, just like here: https://libraries.io/bower/android-app-banner/tags (https://github.com/SpartzInc/android-app-banner/tags)

**Comment by DaSchTour** [comment]
Because nobody added git tags. No proper release workflow.

**Comment by ghost** [comment]
@dfcreative could you please publish tags for this repo?

```
git clone https://github.com/kudago/smart-app-banner.git

git tag -a v1.0.0 -m "Version 1.0.0" 4fd8a7876c118e392274c64dd9d0a6ee89b16674
git push origin v1.0.0

git tag -a v1.3.0 -m "Version 1.3.0" 15aabbf49f737db61526429c525de3ec5a730964
git push origin v1.3.0
```

Thanks. I also created PR #63 so that repo could be added to [travis-ci](http://travis-ci.org) and automating version publishing for bower and npm.

**Comment by dy** [comment]
Pushed tags. Please tell if it worked.

**Comment by ghost** [comment]
Thanks a lot! Works great now.

I think now we can close  #18, #37, #59

**Comment by dy** [comment]
Great!

**Comment by kryptografisch** [comment]
need more tags please. missing all tags in bower since 1.3.0
