### ISSUE TITLE
1.3.1 has breaking changes

### ISSUE THREAD

**Issue by sgtpepper43** [kudago/smart-app-banner#69]
You moved your css files, which is a very, very big breaking change. You need to bump to `2.0.0` if you're going to move public files people have to reference. Your docs even say to reference the css file like so:
```html
<link rel="stylesheet" href="node_modules/smart-app-banner/smart-app-banner.css" type="text/css" media="screen">
```
So everybody's been referencing it there, not in `dist`, so this is a breaking change, not a "patch".

**Comment by sgtpepper43** [comment]
I'm still pissed about this but it's been two years with no response from the maintainer.

**Comment by dy** [comment]
Don't be pissed off. Fixed.
There is no single maintainer for this package.
