### ISSUE TITLE
Is this package dead? Last code merge was Nov 7, 2016

### ISSUE THREAD

**Issue by TSMMark** [kudago/smart-app-banner#90]
15 open and active PRs like #80, but no word from @dfcreative. I am worried to use this package.

**Comment by lucaboieru** [comment]
It seems to be dead. I commented on some PRs few days ago. Still no response.

**Comment by dy** [comment]
@TSMMark @lucaboieru yeah, I basically stopped maintaining that, hoping that the guys from @kudago/frontenders take care of it. Just because there are too many irrelevant PRs with long discussions and I never use this package in any of my projects...
Yet merged the indicated PR.

**Comment by dy** [comment]
If anyone wants I can provide access to the repo to help maintaining that, anybody? @TSMMark @lucaboieru @glibin @iamstarkov @eirikfro @adeyahya @GabLeRoux @fliptheweb @jeffda @tomek-f @sundbry

**Comment by GabLeRoux** [comment]
Hi @dfcreative 
Thanks for notifying. I'm using this in a project and the library still works well for our needs. I didn't do lots of changes here but I think I can give a hand.

I can't say I'll have a lot of time to maintain this, but I could take some time to review a few PRs out there and merge some of them. I'd really like to see some travis integration for this repository btw.

**Comment by joernroeder** [comment]
Hi @dfcreative @GabLeRoux 
I've forked this repo today and did some changes (fixes and new features) as well. I'd love to push them back to an upstream repo and create a bunch of (small) pull requests.

let me know what you think, in the meantime i'm using my [development branch](https://github.com/joernroeder/smart-app-banner/tree/development) with all individual features merged in.

**Comment by GabLeRoux** [comment]
I [compared your development branch with master](https://github.com/kudago/smart-app-banner/compare/master...joernroeder:development) and it looks good to me. I suppose you can send a PR, I'm not in the maintainers right now, but I can at least review things ;)

Edit: I'm in the maintainers now 🎉  I'll have a look shortly :)

**Comment by joernroeder** [comment]
@GabLeRoux yeah sounds good! I'll open a pull request tomorrow morning :)

**Comment by TSMMark** [comment]
I reviewed @joernroeder branch as well, lgtm.

**Comment by dy** [comment]
@TSMMark @GabLeRoux @joernroeder ok added you to collabs, please be wise in making decisions and do not overcomplicate workflow/bundling. I could not find @TSMMark and @GabLeRoux in npm, so added only @joernroeder as npm owner.
Cheers and be considerate in merging PRs.

**Comment by GabLeRoux** [comment]
https://www.npmjs.com/~gableroux ;)
