### ISSUE TITLE
Android problem: banner always redirects to store, even if app is installed.

### ISSUE THREAD

**Issue by noimangil** [kudago/smart-app-banner#91]
even if the user already installed the app, the banner still sends him to the store.
is there a way to prevent that ? 

is it working differently to anyone ?

**Comment by Nicolai8** [comment]
Hi, @noimangil. As I know, there is no way to know what applications you have installed from the browser. So, this is normal behavior.

**Comment by TSMMark** [comment]
@Nicolai8 is correct. I will add that users should be able to open the app from the app store if they already have it installed.
